name: CI Inicial

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      
      - name: Instalar dependências
        working-directory: app
        run: npm ci

      - name: Executar testes
        working-directory: app
        run: npm test -- --coverage --reporters=default --reporters=jest-junit

      
      #- name: Excluir resultados
      #  working-directory: app/test-results
      #  run: rm -rvf junit.xml

      - name: Publish Test Results / Publicar Resultado dos Testes
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            app/test-results/*.xml
            app/test-results/*.trx
            app/test-results/*.json
      
      - name: Lint
        working-directory: app
        run: npm run lint --if-present
  
